/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clube;

/**
 *
 * @author diego
 */
public class Tela extends javax.swing.JFrame {

    Clube barcelona = new Clube();
    Clube realMadrid = new Clube();

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnVitoria01 = new javax.swing.JButton();
        btnDerrota1 = new javax.swing.JButton();
        btnEmpate1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblPontos1 = new javax.swing.JLabel();
        lblVitorias1 = new javax.swing.JLabel();
        lblDerrotas1 = new javax.swing.JLabel();
        lblEmpates1 = new javax.swing.JLabel();
        lblVitorias2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblDerrotas2 = new javax.swing.JLabel();
        lblEmpates2 = new javax.swing.JLabel();
        btnVitoria2 = new javax.swing.JButton();
        btnDerrota2 = new javax.swing.JButton();
        btnEmpate2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblPontos2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel1.setText("Barcelona");

        btnVitoria01.setText("Registrar vitória");
        btnVitoria01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitoria01ActionPerformed(evt);
            }
        });

        btnDerrota1.setText("Registrar derrota");
        btnDerrota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrota1ActionPerformed(evt);
            }
        });

        btnEmpate1.setText("Registrar empate");
        btnEmpate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpate1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Vitórias:");

        jLabel4.setText("Empates:");

        jLabel5.setText("Derrotas:");

        lblPontos1.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblPontos1.setForeground(new java.awt.Color(28, 66, 192));
        lblPontos1.setText("0 pts");

        lblVitorias1.setText("0");

        lblDerrotas1.setText("0");

        lblEmpates1.setText("0");

        lblVitorias2.setText("0");

        jLabel2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        jLabel2.setText("Real Madrid");

        lblDerrotas2.setText("0");

        lblEmpates2.setText("0");

        btnVitoria2.setText("Registrar vitória");
        btnVitoria2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVitoria2ActionPerformed(evt);
            }
        });

        btnDerrota2.setText("Registrar derrota");
        btnDerrota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerrota2ActionPerformed(evt);
            }
        });

        btnEmpate2.setText("Registrar empate");
        btnEmpate2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpate2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Vitórias:");

        jLabel7.setText("Empates:");

        jLabel8.setText("Derrotas:");

        lblPontos2.setFont(new java.awt.Font("Open Sans", 1, 14)); // NOI18N
        lblPontos2.setForeground(new java.awt.Color(28, 66, 192));
        lblPontos2.setText("0 pts");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmpate1)
                            .addComponent(btnVitoria01)
                            .addComponent(btnDerrota1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDerrotas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblVitorias1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmpates1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPontos1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEmpate2)
                            .addComponent(btnVitoria2)
                            .addComponent(btnDerrota2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDerrotas2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblVitorias2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblEmpates2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPontos2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblPontos2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVitoria2)
                            .addComponent(jLabel6)
                            .addComponent(lblVitorias2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmpate2)
                            .addComponent(jLabel7)
                            .addComponent(lblEmpates2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDerrota2)
                            .addComponent(jLabel8)
                            .addComponent(lblDerrotas2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblPontos1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnVitoria01)
                            .addComponent(jLabel3)
                            .addComponent(lblVitorias1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEmpate1)
                            .addComponent(jLabel4)
                            .addComponent(lblEmpates1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDerrota1)
                            .addComponent(jLabel5)
                            .addComponent(lblDerrotas1))))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDerrota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrota1ActionPerformed
        barcelona.registrarDerrota();
        lblDerrotas1.setText(barcelona.getDerrotas().toString());
    }//GEN-LAST:event_btnDerrota1ActionPerformed

    private void btnEmpate1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpate1ActionPerformed
        barcelona.registrarEmpate();
        lblEmpates1.setText(barcelona.getEmpates().toString());
        lblPontos1.setText(barcelona.getPontos().toString()+ " pts");
    }//GEN-LAST:event_btnEmpate1ActionPerformed

    private void btnDerrota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerrota2ActionPerformed
        realMadrid.registrarDerrota();
        lblDerrotas2.setText(realMadrid.getDerrotas().toString());
    }//GEN-LAST:event_btnDerrota2ActionPerformed

    private void btnEmpate2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpate2ActionPerformed
        realMadrid.registrarEmpate();
        lblEmpates2.setText(realMadrid.getEmpates().toString());
        lblPontos2.setText(realMadrid.getPontos().toString()+ " pts");
    }//GEN-LAST:event_btnEmpate2ActionPerformed

    private void btnVitoria01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitoria01ActionPerformed
        barcelona.registrarVitoria();
        lblVitorias1.setText(barcelona.getVitorias().toString());
        lblPontos1.setText(barcelona.getPontos().toString()+ " pts");
    }//GEN-LAST:event_btnVitoria01ActionPerformed

    private void btnVitoria2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVitoria2ActionPerformed
        realMadrid.registrarVitoria();
        lblVitorias2.setText(realMadrid.getVitorias().toString());
        lblPontos2.setText(realMadrid.getPontos().toString() + " pts");
    }//GEN-LAST:event_btnVitoria2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDerrota1;
    private javax.swing.JButton btnDerrota2;
    private javax.swing.JButton btnEmpate1;
    private javax.swing.JButton btnEmpate2;
    private javax.swing.JButton btnVitoria01;
    private javax.swing.JButton btnVitoria2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblDerrotas1;
    private javax.swing.JLabel lblDerrotas2;
    private javax.swing.JLabel lblEmpates1;
    private javax.swing.JLabel lblEmpates2;
    private javax.swing.JLabel lblPontos1;
    private javax.swing.JLabel lblPontos2;
    private javax.swing.JLabel lblVitorias1;
    private javax.swing.JLabel lblVitorias2;
    // End of variables declaration//GEN-END:variables
}
